### ISSUE TITLE
When disc created why it is having a too much gap?

### ISSUE THREAD

**Issue by sujena2407** [Elzian-Agro/Dev-Blog-Site#11]
![Screenshot 2022-07-04 153249](https://user-images.githubusercontent.com/79244758/177132813-09674628-13ba-404c-a1be-263a24fcf459.jpg)

**Comment by RazeenRamzy** [comment]
It's because of alignment. we have to change the alignment of the content.

**Comment by RazeenRamzy** [comment]
fixed this issue...
![image](https://user-images.githubusercontent.com/73276893/177183375-7147db11-e82c-4414-964c-cac0d246c0fc.png)
