### ISSUE TITLE
Images are not presented in a proper way

### ISSUE THREAD

**Issue by RazeenRamzy** [Elzian-Agro/Dev-Blog-Site#13]
Images are not in the proper way. size of the images are different from each other.
![image](https://user-images.githubusercontent.com/73276893/177184563-d71d6268-21ec-4a1c-aa24-52cbcc8a7e2d.png)

**Comment by pankajan05** [comment]
![image](https://user-images.githubusercontent.com/37388848/177237994-58243351-f86f-4e81-a3fd-be7903a7e0e4.png)

**Comment by RazeenRamzy** [comment]
The logo issue fixed.
![image](https://user-images.githubusercontent.com/73276893/177254708-0b27a228-343d-4ebd-b21c-e6642e1a28dd.png)

**Comment by RazeenRamzy** [comment]
Portfolio images are updated 
![image](https://user-images.githubusercontent.com/73276893/177479007-c52536ad-9f21-4fd7-816c-24c38a88e9e6.png)
