### ISSUE TITLE
The Banner letter needs to be visible

### ISSUE THREAD

**Issue by pankajan05** [Elzian-Agro/Dev-Blog-Site#18]
![image](https://user-images.githubusercontent.com/37388848/177238087-02499c33-f3de-45c6-93ee-698f1a342b92.png)

Banner any innovative ways you needs to find. E.g: ThreeJS.
doc: https://threejs.org/docs/
examples: https://threejs.org/examples/

**Comment by Abi1327** [comment]
I have changed the font color

**Comment by Abivarna** [comment]
I couldn't able to find the Banner's image line

**Comment by Abi1327** [comment]
I couldn't able to find the banner's image code in the html file

**Comment by piumal96** [comment]
you can edit with this css.
![image](https://user-images.githubusercontent.com/75016776/177718222-59188c79-063d-438e-8c19-bd08ddb202dc.png)

**Comment by Abi1327** [comment]
ok

**Comment by Abi1327** [comment]
I have removed the background but the logo also have gone

**Comment by piumal96** [comment]
i think logo removed before assigned person, i had done with photoshop. @RazeenRamzy  are you work with logo ?

**Comment by RazeenRamzy** [comment]
> I have removed the background but the logo also have gone

No, it's because @piumal96 attached the logo to the banner. That's why the logo is unavailable once you change the background image.

**Comment by neranjanpriyashantha** [comment]
Added css animation to banner
