### ISSUE TITLE
Write Blog

### ISSUE THREAD

**Issue by pankajan05** [Elzian-Agro/Dev-Blog-Site#19]
Everyone Needs to write at least one blog.

**Comment by RazeenRamzy** [comment]
The IoT blog is updated. I added some additional content to it.

**Comment by sujena2407** [comment]
The sql blog is updated. I added some additional content.

**Comment by Abi1327** [comment]
The Java block is updated.I added some additional content there.

**Comment by neranjanpriyashantha** [comment]
Updated the python blog content.

**Comment by Thejani1** [comment]
The Web programming blog is updated. I Added some additional content to it.

**Comment by piumal96** [comment]
Updated the blockchain blog content.
