### ISSUE TITLE
Dev Road Map

### ISSUE THREAD

**Issue by pankajan05** [Elzian-Agro/Dev-Blog-Site#22]
![image](https://user-images.githubusercontent.com/37388848/177240104-53804972-fd48-4ec2-9103-608bfe2b68a1.png)

Needs to write the content according to our dev road map.

**Comment by RazeenRamzy** [comment]
this issue fixed

![image](https://user-images.githubusercontent.com/73276893/177337758-1f91eaf1-07fe-48d6-9b4c-76cb638aa4c8.png)
