### ISSUE TITLE
Send mail using the contact us form

### ISSUE THREAD

**Issue by pankajan05** [Elzian-Agro/Dev-Blog-Site#23]
![image](https://user-images.githubusercontent.com/37388848/177240425-4bad6f62-072e-4581-8b3e-f503fb8e6d1f.png)

Libray: js and EmailJs

Change the button color to the #06a223

**Comment by neranjanpriyashantha** [comment]
Fixed the issue.
Messages will be received through this email "careers@elzian.com"
