### ISSUE TITLE
need to add ABSTRACT for report

### ISSUE THREAD

**Issue by Thejani1** [Elzian-Agro/Dev-Blog-Site#26]
![ewPNG](https://user-images.githubusercontent.com/107385282/177279665-1e2bb5e5-2952-4b49-b985-8bf8210279dc.PNG)

**Comment by RazeenRamzy** [comment]
@thenukagunawardana You can use the following link to edit the report.

https://docs.google.com/document/d/1Gj0j69Go88hPZGo5Q1cJfuL9tE2skUHn/edit?usp=sharing&ouid=105856518530847106049&rtpof=true&sd=true

**Comment by thenukagunawardana** [comment]
![image](https://user-images.githubusercontent.com/52916808/177462257-86a7fa8b-c25b-482a-bef0-6eba6ba30f79.png)

Done
