### ISSUE TITLE
why after clone,not show web page images 

### ISSUE THREAD

**Issue by piumal96** [Elzian-Agro/Dev-Blog-Site#4]

**Comment by pankajan05** [comment]
Master Branch is in deployment.  URL : https://elzian-agro.github.io/Dev-Blog-Site/

**Comment by RazeenRamzy** [comment]
But even though we deployed the website on the GitHub page, we cannot properly see the images...
![image](https://user-images.githubusercontent.com/73276893/177027629-e47b8edb-d74d-40c7-9ddb-050297bae8b9.png)

**Comment by piumal96** [comment]
i think want to add js and css files (Boostrap files) only showing basic html
