### ISSUE TITLE
Add Elzian Agro logo to the website.

### ISSUE THREAD

**Issue by pankajan05** [Elzian-Agro/Dev-Blog-Site#42]
Logo is in our Elzian Agro website: https://agro.elzian.com/

**Comment by thenukagunawardana** [comment]
![image](https://user-images.githubusercontent.com/52916808/178094533-1a78f7ef-acb7-421c-80e4-862fe9d24f45.png)

Added Elzian Agro Logo

**Comment by thenukagunawardana** [comment]
@pankajan05 Is this logo right or does it need to be changed ?

**Comment by thenukagunawardana** [comment]
![Capture](https://user-images.githubusercontent.com/52916808/178220519-ba7800d6-641e-4055-bb94-4881440040e2.PNG)
![logo_1](https://user-images.githubusercontent.com/52916808/178220524-7dfe2581-2452-4f84-b0b8-97bd65e2b20e.PNG)

Are these changes acceptable? @pankajan05

**Comment by pankajan05** [comment]
It is not acceptable. It needs to attractive. The position and padding wise it is not good.
