### ISSUE TITLE
can't get scrennshorts for report. I can see like this 

### ISSUE THREAD

**Issue by Thejani1** [Elzian-Agro/Dev-Blog-Site#5]
![Capture](https://user-images.githubusercontent.com/107385282/177026372-9b145ba1-168c-40a7-953b-94cb84d5543b.PNG)

**Comment by RazeenRamzy** [comment]
![image](https://user-images.githubusercontent.com/73276893/177028639-14602b3f-1d4a-42c3-ab40-beb5a8da43ae.png)
I can able to see the image. I think because of CSS and JS file these issues are occurring. to sort out this issue, will ask help from Mr. pankajan at tomorrow's meeting.
